switch to `conf` from `apache` formatting
this broke page builds for me. took an email to github support to figure out
why. here's the response:

> I took a look at our internal logs and found this:
> Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2016-04-23-recovering-openid.md': undefined method `include?' for nil:NilClass
> I took a look at that file and found this:
> ```apache
> There is a bug in the current version of Jekyll that has issues with apache highlighting. If you change that to:
> ```conf